# HTTP模块设置
http:
  host: localhost
  port: 9044

# 上传模块的相关设置

upload:
  path: uploads
  image: image
  thumbnail: thumbnail
  thumbnailmaxwidth: 300
  thumbnailmaxheight: 300
  allowtype:    # 如果是空数组，那么会允许任意文件后缀名
    - .jpg
    - .jpeg
    - .png
    - .svg
    - .gif
    - .bmp
    - .ico
  maxsize: 10485760 # 1024 * 1024 * 10, // 10M