# HTTP模块设置
http:
  host: localhost                               # 监听地址
  port: 9044                                    # 监听端口

# 上传模块的相关设置

upload:
  path: uploads                                 # 上传文件的保存目录名，相对于当前目录
  image: image                                  # path的子目录，图片保存的目录名，
  thumbnail: thumbnail                          # path的字目录，缩略图保存的目录名
  thumbnailmaxwidth: 300                        # 缩略图的最大宽度
  thumbnailmaxheight: 300                       # 缩略图的最大高度
  allowtype:                                    # 如果是空数组，那么会允许任意文件后缀名
    - .jpg
    - .jpeg
    - .png
    - .svg
    - .gif
    - .bmp
    - .ico
  maxsize: 10485760                             # 上传文件的最大大小，默认10M